### PR TITLE
Refactor ModuleName class to TaskName

### PR DESCRIPTION
**Pull request by geraldfan**
2. Refactor ModuleNameTest to TaskNameTest
3. Refactor ModuleNameContainsKeywordsPredicateTest to TaskNameContainsKeywordsPredicateTest
4. Update json files
5. Update Command classes and CommandTests
6. Update fxml files
7. Update TaskCard class
8. Update util classes

### CODE REVIEW

**Review by austenjs — APPROVED** [review]
LGTM

**Review by austenjs — CHANGES_REQUESTED** [review]
Failed the CI

**Comment by danielonges** [comment]
Looks like some of the tests weren't refactored from ModuleName to TaskName after the merging with my previous branch

**Comment by danielonges** [comment]
lgtm

**Pull request merged**
